### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by barak** [Echsecutor/coffee#1]
My only issue with this is that I didn't know about version 5! I maintain the Debian latex-coffee-stains package, https://github.com/barak/latex-coffee-stains, and my inclination would be to switch from v4 to your v5. But I note that you include both in your repo, is that an implicit recommendation to keep v4 around in parallel?

**Comment by Echsecutor** [comment]
Hi @barak !
Nice! By the time I created this repository, there was no version of coffee on github, neither a debian package (at least I could not find either).

The coffee4 in my repo is there for historic reasons, I would recommend using my moddified coffee5 version. ;)

**Comment by Echsecutor** [comment]
I have pulled in your updates and removed version4 in 759ad12462ca0bc81de4ada88c4961904c8249b0

**Comment by barak** [comment]
Cool.

(I wonder if there would be a nice way to include steganographic information in the coffee stains, e.g., git commit IDs for purposes of change tracking.)
